### ISSUE TITLE
Convert to char array?

### ISSUE THREAD

**Issue by EuphoriaCelestial** [nickgammon/BigNumber#13]
I am trying to do the Diffie Hellman key exchange here. It require a very very large prime number, so I end up using this library. But then the key must be in char[] type.
So is there any proper way to convert?

**Comment by nickgammon** [comment]
Yes, the toString function does that. For example:

```c++
// function to display a big number and free it afterwards
void printBignum (BigNumber & n)
{
  char * s = n.toString ();
  Serial.println (s);
  free (s);
}  // end of printBignum
```
